image: trzeci/emscripten:1.39.0
tasks:
  - init: wget https://github.com/jeromewu/docker-workspace/raw/master/vim.zip -O /tmp/vim.zip &> /dev/null && unzip /tmp/vim.zip -d /home/gitpod &> /dev/null
    command: export PATH=$PATH:/emsdk_portable/emscripten/tag-1.39.0:/emsdk_portable/emscripten/sdk:/emsdk_portable/node/current/bin
