name: CI

on:
  push:
    branches:
    - n4.1.4-js
  pull_request:
    branches:
    - n4.1.4-js

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build ffmpeg-core.js
      run: |
        bash ./build-with-docker.sh
    - uses: actions/upload-artifact@master
      with:
        name: ffmpeg-core
        path: dist
    - uses: actions/upload-artifact@master
      with:
        name: ffmpeg-core-wasm
        path: dist-wasm
