name: CI

on:
  push:
    branches:
    - n4.1.4-js
  pull_request:
    branches:
    - n4.1.4-js

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: List content of repository
      run: ls
    - name: Check docker info
      run: |
        docker info
